- src/main/java/com/project/thisvsthat/chat/controller/ChatController.java
- src/main/resources/static/css/style.css
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/index.html
- src/main/resources/templates/layout/layout.html
> Fix: css 원본으로 수정 후 적용

- src/main/java/com/project/thisvsthat/admin/controller/AdminController.java
- src/main/java/com/project/thisvsthat/admin/service/AdminService.java
- src/main/java/com/project/thisvsthat/common/repository/PostRepository.java
- src/main/resources/static/js/admin.js
- src/main/resources/templates/admin/admin.html
신고글 복구/삭제 일괄 작업으로 기능 구현 했습니다. 확인 부탁드립니다 :)
> Feat: 신고글 복구/삭제 일괄 작업 기능 구현 완료

- src/main/resources/static/css/style.css
- src/main/resources/templates/fragments/components.html
display:flex로 바꾸고 정렬이 깨져서 확인 후 수정했습니다.
컴포넌트 html 파일에 css/js 경로 복붙하다 바뀌는 바람에;; 다시 바꿔서 올렸습니다..
> Design: a태그 css 속성 추가

- src/main/java/com/project/thisvsthat/post/PostController.java
- src/main/resources/static/css/post.css
- src/main/resources/templates/post/createPost.html
- src/main/resources/templates/post/postDetail.html
- src/main/resources/templates/post/updatePost.html
- 게시물 작성,수정,상세 페이지 html, css 작업 완료
- hover 및 애니메이션 효과는 기능 작업 후 추가 할 예정
> Feat: 게시물 작성,수정,상세 html 및 css 작업

- src/main/java/com/project/thisvsthat/common/dto/UserDTO.java
- src/main/java/com/project/thisvsthat/common/entity/User.java
- src/main/java/com/project/thisvsthat/myPage/DAO/MyPageDAO.java
- src/main/java/com/project/thisvsthat/myPage/controller/MyPageController.java
- src/main/java/com/project/thisvsthat/myPage/service/MyPageService.java
- src/main/resources/static/css/myPage.css
- src/main/resources/templates/myPage/myPage.html
- 마이페이지 html&css 작업 1차 완료
- 닉네임 수정 기능 완료
--> '탈퇴하기' 글씨 : 위치 등 디자인은 추후에 추가 수정할 예정
> Feat: 마이페이지 html 및 css 작업

- src/main/java/com/project/thisvsthat/admin/controller/AdminController.java
- src/main/java/com/project/thisvsthat/admin/service/AdminService.java
- src/main/java/com/project/thisvsthat/common/entity/SpamFilter.java
- src/main/java/com/project/thisvsthat/common/repository/SpamFilterRepository.java
- src/main/java/com/project/thisvsthat/common/service/SpamFilterService.java
- src/main/resources/static/css/admin.css
- src/main/resources/static/js/admin.js
- src/main/resources/templates/admin/admin.html
금지 키워드 추가 기능 / 중복 방지 기능 구현 했습니다.
> Feat:  금지 키워드 추가 기능 완료. - 중복 키워드 등록 방지 기능 구현.

- src/main/java/com/project/thisvsthat/admin/controller/AdminController.java
- src/main/java/com/project/thisvsthat/common/repository/SpamFilterRepository.java
- src/main/java/com/project/thisvsthat/common/service/SpamFilterService.java
- src/main/resources/static/js/admin.js
- src/main/resources/templates/admin/admin.html
> Feat:  금지 키워드 삭제 기능 완료.

- src/main/resources/static/css/post.css
- src/main/resources/static/js/post.js
- src/main/resources/templates/post/createPost.html
- src/main/resources/templates/post/postDetail.html
- src/main/resources/templates/post/updatePost.html
- 공유 버튼 클릭 시 현재 url 클립보드에 복사
- 뒤로 가기 버튼 클릭 시 뒤로 가기
- post 관련 페이지(상세,등록,수정)에서 링크 관련된 요소들 cursor: pointer 추가
(모바일 위주라 필요없는 css긴 하지만, 데스크탑에서 접속할 것도 고려하여 추가하였습니다.)
> Feat: 공유 버튼 및 뒤로 가기 버튼 구현

- src/main/java/com/project/thisvsthat/auth/config/SecurityConfig.java
- src/main/java/com/project/thisvsthat/auth/controller/OAuthController.java
- src/main/java/com/project/thisvsthat/auth/dto/SignupRequestDTO.java
- src/main/java/com/project/thisvsthat/auth/service/OAuthService.java
- src/main/java/com/project/thisvsthat/image/service/S3Service.java
- src/main/resources/static/css/auth.css
- src/main/resources/static/js/auth/auth-signup.js
- src/main/resources/templates/auth/signup.html
- 회원가입 페이지에서 이미지 수정 기능 구현
- 로그아웃 요청 시 리디렉트하는 url "/" 메인 페이지로 수정
> Feat: 회원가입 페이지 프로필 이미지 수정 기능 구현

- src/main/java/com/project/thisvsthat/chat/config/RedisConfig.java
- src/main/java/com/project/thisvsthat/chat/controller/ChatController.java
- src/main/java/com/project/thisvsthat/chat/dto/ChatMessage.java
- src/main/java/com/project/thisvsthat/chat/service/ChatService.java
- src/main/java/com/project/thisvsthat/chat/util/RedisPublisher.java
- src/main/java/com/project/thisvsthat/chat/util/RedisSubscriber.java
- src/main/java/com/project/thisvsthat/common/controller/VoteController.java
- src/main/java/com/project/thisvsthat/common/repository/ChatRoomRepository.java
- src/main/java/com/project/thisvsthat/common/repository/UserRepository.java
- src/main/java/com/project/thisvsthat/image/service/ImageService.java
- src/main/java/com/project/thisvsthat/image/service/S3Service.java
- src/main/resources/static/css/chat/chat-room.css
- src/main/resources/static/js/chat/chat-profile-popup.js
- src/main/resources/static/js/chat/chat-room.js
- src/main/resources/templates/chat/chat-room.html
- src/main/resources/templates/post/postDetail.html
- 실시간 채팅 기능 구현
- 채팅방 인원수 실시간으로 변경
- 이전 메시지 불러오는 기능 구현
- 투표 현황 불러오기
- 투표 현황 업데이트 버튼
- 채팅방 타이틀 애니메이션 추가
- 채팅 프로필 사진 s3로 저장
https://github.com/user-attachments/assets/7c5367a3-1ac2-4442-968d-71a034ad7338
> Feat: 실시간 채팅 기능 구현, 투표 현황 

- src/main/resources/static/css/admin.css
- src/main/resources/static/css/style.css
- src/main/resources/templates/admin/admin.html
> Design: 어드민 페이지 레이아웃 수정.

- src/main/resources/static/css/myPage.css
- src/main/resources/templates/myPage/myPage.html
> Fix: 마이페이지 게시물 css 수정

- src/main/resources/static/css/index.css
- src/main/resources/static/css/myPage.css
- src/main/resources/templates/myPage/myPage.html
- 메인 페이지: 돋보기 아이콘 UI 깨지는 문제 수정
- 마이 페이지: 닉네임 수정 UI 깨지는 문제 수정
> Design: 메인 페이지 & 마이 페이지 UI 수정

- src/main/java/com/project/thisvsthat/chat/config/RedisConfig.java
- src/main/java/com/project/thisvsthat/chat/controller/ChatController.java
- src/main/java/com/project/thisvsthat/chat/service/ChatService.java
- src/main/java/com/project/thisvsthat/chat/service/ChatSubscriptionService.java
- src/main/java/com/project/thisvsthat/chat/util/RedisPublisher.java
- src/main/java/com/project/thisvsthat/chat/util/RedisSubscriber.java
- src/main/resources/static/css/chat/chat-profile-popup.css
- src/main/resources/static/css/chat/chat-room.css
- src/main/resources/static/css/style.css
- src/main/resources/static/js/chat/chat-room.js
- src/main/resources/templates/chat/chat-room.html
- 채팅 기능에 레디스 구독이 되지 않던 오류를 수정
- 소소한 디자인 수정
> Fix: 레디스 구독 설정 추가

- src/main/java/com/project/thisvsthat/common/repository/ReportRepository.java
- src/main/java/com/project/thisvsthat/common/service/ReportService.java
- src/main/java/com/project/thisvsthat/post/controller/PostController.java
- src/main/java/com/project/thisvsthat/post/service/PostService.java
- src/main/resources/templates/post/postDetail.html
- 중복 신고 불가
- 신고 1회 = 유저 상태 REPORTED, 게시물 상태 BLINDED로 변화
--> 추후에 코드 단순화 필요 (중복 신고 alert가 안떠서 중복 신고 안내 관련 코드 늘어남)
> Feat: 신고 카운트 작업 완료

- src/main/java/com/project/thisvsthat/chat/controller/ChatController.java
- src/main/java/com/project/thisvsthat/common/service/SpamFilterService.java
- src/main/resources/static/css/chat/chat-room.css
- src/main/resources/static/js/chat/chat-room.js
- src/main/resources/templates/chat/chat-room.html
- src/main/resources/templates/post/postDetail.html
- 투표 현황 접기/펴기 기능 구현
- 입력 필드 높이 조절 및 500자 제한 기능 추가
- 프로필 설정 팝업 기본 선택 옵션 변경
- 제목 동적 너비 적용 및 스크롤 메서드 변경
- 뒤로가기 기능 구현
https://github.com/user-attachments/assets/31f0d7c8-d339-468d-bbb9-e575c113d174
- 메시지 전송 시 스팸 필터링 적용
> Feat: 투표 현황 접기/펴기 기능 구현, 스팸 필터 적용 및 프로필 설정 UI 개선

- src/main/java/com/project/thisvsthat/chat/controller/ChatController.java
- src/main/java/com/project/thisvsthat/chat/dto/ChatMessage.java
- src/main/java/com/project/thisvsthat/chat/redis/logger/RedisConnectionLogger.java
- src/main/java/com/project/thisvsthat/chat/redis/pubsub/RedisPublisher.java
- src/main/java/com/project/thisvsthat/chat/redis/pubsub/RedisSubscriber.java
- src/main/java/com/project/thisvsthat/chat/redis/pubsub/RedisSubscriptionService.java
- src/main/java/com/project/thisvsthat/chat/service/ChatMessageService.java
- src/main/java/com/project/thisvsthat/chat/service/ChatUserService.java
- src/main/resources/static/css/chat/chat-room.css
- src/main/resources/static/js/chat/chat-room.js
- src/main/resources/templates/chat/chat-room.html
1. 리팩토링 (Refactor)
- 로그 형식 통일 (📩 [SUCCESS], 🚨 [ERROR] 등 일관된 포맷 적용)
- 메시지 전송 및 저장 관련 성공 로그 추가
2. 기능 개선 (Enhance)
- 메시지에 전송 날짜 추가
3. UI/UX 개선 (Design)
- 말풍선 너비 조정 및 영문 줄바꿈 문제 해결
4. 오류 수정 (Fix)
- 오래된 메시지가 아닌 최근 메시지가 저장되는 오류 수정
> Fix: 채팅 UI 개선 및 메시지 저장 오류 수정

- src/main/java/com/project/thisvsthat/ThisvsthatApplication.java
- src/main/java/com/project/thisvsthat/chat/controller/ChatController.java
- src/main/java/com/project/thisvsthat/chat/redis/config/RedisConfig.java
- src/main/java/com/project/thisvsthat/chat/redis/logger/RedisConnectionLogger.java
- src/main/java/com/project/thisvsthat/chat/redis/pubsub/RedisPublisher.java
- src/main/java/com/project/thisvsthat/chat/redis/pubsub/RedisSubscriber.java
- src/main/java/com/project/thisvsthat/chat/redis/pubsub/RedisSubscriptionService.java
- src/main/java/com/project/thisvsthat/chat/service/ChatMessageService.java
- src/main/java/com/project/thisvsthat/chat/service/ChatUserService.java
- src/main/resources/static/css/chat/chat-room.css
- src/main/resources/static/js/chat/chat-room.js
1. 메시지 발행 시 저장 방식 변경
- Redis 저장 방식 개선 및 DB 저장 비동기 처리 추가
2. 채팅방 입장/퇴장 처리 방식 개선
- 동시성 처리 강화 및 입장/퇴장 로직 개선
- Redis 구독/구독 해제 로직에서 userId를 로그에 포함하여 디버깅 용이성 향상
> Feat: 메시지 발행 및 저장 처리 방식 개선

- src/main/java/com/project/thisvsthat/admin/controller/AdminController.java
- src/main/java/com/project/thisvsthat/common/repository/UserRepository.java
- src/main/resources/static/css/admin.css
- src/main/resources/static/css/style.css
- src/main/resources/static/js/admin.js
- src/main/resources/templates/admin/admin.html
관리자 페이지 작업 시 편의성을 올려 줄 추가 기능 작업 했습니다 :)
> Feat: 어드민 페이지 작업 편의 기능 추가. - 키워드 추가 enter 입력 시 추가 기능. - 팝업 확인 버튼 enter 입력 시 선택 기능 - css 수정

- src/main/java/com/project/thisvsthat/chat/service/ChatRoomService.java
- src/main/java/com/project/thisvsthat/common/entity/ChatRoom.java
- src/main/java/com/project/thisvsthat/common/repository/ChatLogRepository.java
- src/main/java/com/project/thisvsthat/myPage/controller/MyPageController.java
- src/main/java/com/project/thisvsthat/myPage/service/MyPageService.java
- src/main/java/com/project/thisvsthat/post/service/PostService.java
- src/main/resources/static/css/myPage.css
- src/main/resources/static/css/post.css
- src/main/resources/static/js/myPage.js
- src/main/resources/templates/myPage/myPage.html
- 사용자가 참여한 채팅방 조회 가능
- myPage.css 수정
- 신고 카운트 중 게시물 신고 3번 받았을 때 postStatus.BLINDED 로 변경
- 신고 카운트 css 추가
> Feat: 마이페이지 - 채팅방 작업 완료
